# Generated by Django 3.0.4 on 2020-04-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_no',
        ),
    ]
