# Generated by Django 3.0.4 on 2020-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_remove_question_question_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct_answer',
            field=models.BooleanField(null=True),
        ),
    ]
