# Generated by Django 3.0.4 on 2020-04-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_auto_20200404_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
